# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Compile code
          command: cat /dev/null | sbt clean compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      #    - run:
      #        name: Test / Coverage
      #        command: cat /dev/null | sbt coverage test coverageReport

      #    - run:
      #        name: Codecov report
      #        command: bash <(curl -s https://codecov.io/bash)

      # https://discuss.circleci.com/t/gpg-keys-as-environment-variables/28641/3:
      #      - run:
      #          name: set PINENTRY
      #          command: touch ~/.gnupg/gpg.conf && echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf && cat ~/.gnupg/gpg.conf

      #      - run:
      #          name: set tty env var
      #          command: echo "export GPG_TTY=$(tty)" >> $BASH_ENV


      #             echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf && cat ~/.gnupg/gpg.conf
      - run:
          name: Setup GPG
          command: |
            echo -e "$GPG_PUBLIC" | gpg --import
            touch ~/.gnupg/gpg.conf
            echo use-agent >> ~/.gnupg/gpg.conf
            echo pinentry-mode loopback >> ~/.gnupg/gpg.conf
            echo allow-loopback-pinentry >> ~/.gnupg/gpg-agent.conf
            apt-get install gpg-preset-passphrase
            gpg-preset-passphrase -p $GPG_PASSPHRASE
            echo RELOADAGENT | gpg-connect-agent
            echo -e "$GPG_PRIVATE" | gpg --no-tty --passphrase "$GPG_PASSPHRASE" --import

      - run:
          name: Publish
          command: sbt publish